### ISSUE TITLE
Add Vite Support

### ISSUE THREAD

**Issue by GregLahaye** [pixijs/storybook#1]
Firstly, just wanted to say thanks for creating this project - it's exactly what I was looking for.

I am using Vite in my app and was wondering if you'd be open to adding vite support?

I'd be happy to help in the implementation.

**Comment by GregLahaye** [comment]
I've created a PR here: https://github.com/pixijs/storybook/pull/2

**Comment by bildungsroman** [comment]
Hi @Zyie is there any way to merge in Greg's PR or use it as the basis of a @pixi/storybook-vite package with Pixi 8 support? My team really needs this and I'm sure I'm not the only one
